### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by danzsmith53**
Updated grammar and style many places throughout file

Line 14 contains a broken link; it should be updated.

A mention of "trusted platform service" near the end was a surprise as it was not previously defined or mentioned. I am not sure what that means, so I did not edit that area.

### CODE REVIEW

**Comment by mitar** [comment]
> A mention of "trusted platform service" near the end was a surprise as it was not previously defined or mentioned. I am not sure what that means, so I did not edit that area.

I also do not understand that part. Also, it is pretty ugly installation of that on Ubuntu? Using alien and JNI? Is there really not a cleaner way? And what it is for?

**Comment by lzha101** [comment]
Thanks for the patch. Could you make sure you accept the license and add a Signed-off-by to your commit message? 
For the broken line issue, the fix will be included in next release.

**Comment by llly** [comment]
the [SGX_SDK_Developer_Reference](Intel_SGX_SDK_Developer_Reference_Linux_1.8_Open_Source.pdf) provided in [01.org](https://01.org/intel-software-guard-extensions/downloads) has a section “Trusted Platform Service Functions” which lists interfaces sgx_create_pse_session(),  sgx_get_trusted_time(), etc.  These functions are for trusted platform service.

**Comment by haitaohuang** [comment]
close this one to submit another one with proper sign off

**Pull request closed without merging**
