### PR TITLE
typo s/msssage/message

### PR DESCRIPTION
**Pull request by veorq**

### CODE REVIEW

**Comment by zhaohuidu** [comment]
No real change

**Comment by andyzyb** [comment]
The typo is from the name, seems it can be accepted.  But please review the contributing.md and make sure you accept the license.  Each patch also needs a signed-off-by before it can be accepted.

**Comment by zhaohuidu** [comment]
veorq ,
   Would you please help to sign off as the CONTRIBUTING.md file?

**Comment by veorq** [comment]
Signed-off-by: Jean-Philippe Aumasson <jeanphilippe.aumasson@gmail.com>

Is that sufficient?

**Comment by andyzyb** [comment]
signed-off-by should be in the patch commit message

**Comment by llly** [comment]
We will not merge below pull request as it has no signed-off-by, but we can fix this typo in our code and release it next time.

**Pull request closed without merging**
