### PR TITLE
Fix build issues on g++-7

### PR DESCRIPTION
**Pull request by kaimast**
Throw specifiers (except nothrow) shall not be used anymore. Modern versions of g++ create an error message about that.
Also, fallthroughs in switch statements need to explicitly specified now so the compiler does not complain.

### CODE REVIEW

**Comment by Smattr** [comment]
Part of this seems to change third-party code. Looks as if the external [addressed this](https://github.com/leethomason/tinyxml2/commit/3cc6f5c6f2184ed56fb13353ef5d03d38f00dac6) in a different way that's backwards compatible with non-C++11 compilers. It might be simpler in the long term to resync with upstream instead.

**Comment by chrisr3** [comment]
Are you sure this is correct? GCC 7.2 only complains about `throw(std::bad_alloc)` on two `new` operators for me, and it also requires that I remove them from _both_ the prototypes _and_ the C++ function bodies.

**Comment by llly** [comment]
@chrisr3 Agree. C++ function bodies should be changed.

**Comment by kaimast** [comment]
Yeah you're right. The makefile in the SDK is a little buggy and didn't actually rebuild the cpp file when I changed the header.

Pushed the cpp stuff too.

**Pull request merged**
